---
version: "3.8"

services:
  dokken:
    image: dokken
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./app:/dokken/app
      - ./routes:/dokken/routes
      - ./php-docker:/dokken/php-docker
      - ./resources:/dokken/resources
      - ./public:/dokken/public
      - ./vendor:/dokken/vendor
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/dokken/.env
    ports:
      - 8080:80
